DROP TABLE `#__getbible_books`;
DROP TABLE `#__getbible_chapters`;
DROP TABLE `#__getbible_verses`;
DROP TABLE `#__getbible_versions`;
DROP TABLE `#__getbible_setbooks`;
DROP TABLE `#__getbible_highlights`;
DROP TABLE `#__getbible_notes`;
DROP TABLE `#__getbible_tags`;
DROP TABLE `#__getbible_taged`;